### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by nem0** [JakubLukas/NewEngine#1]

**Comment by Alan-FGR** [comment]
yes it is

**Comment by JakubLukas** [comment]
Not cool :D it is just semi-dead

**Comment by Alan-FGR** [comment]
:trollface:

**Comment by nem0** [comment]
Is it deader than Loomikz?

**Comment by Alan-FGR** [comment]
Loomi*what*? That one is so dead and was so irrelevant nobody not even remembers it anymore :trollface:

**Comment by nem0** [comment]
So, does it mean it's dead?

**Comment by Alan-FGR** [comment]
@nem0 yes
